*&---------------------------------------------------------------------*
*& Module Pool       ZJS_BILLING_SYSTEM
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
PROGRAM zjs_billing_system.

INCLUDE : zjs_billing_system_data,
          zjs_billing_system_pbo,
          zjs_billing_system_pai,
          zjs_billing_system_logo.
